# Modified from https://www.fastruby.io/blog/ruby/code-quality/how-we-use-rubocop-and-standardrb.html
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sequel
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - public/**/*

RSpec:
  Enabled: true # enable rubocop-rspec cops

Performance:
  Enabled: true

Rake:
  Enabled: true

Sequel:
  Enabled: true

RSpec/DescribeMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/HeredocIndentation:
  Enabled: false
