extends: ["spectral:oas"]
rules:
  operation-description: off
  additional-properties-with-properties:
    description: "Any element with properties also has additionalProperties false"
    given: $..[?(@ && @.properties)]
    severity: error
    then:
      - field: additionalProperties
        function: defined
      - field: additionalProperties
        function: falsy
  responses-required-with-properties:
    description: "Any responses schema with properties also has required array"
    given: $.paths..responses..[?(@ && @.properties)]
    severity: error
    then:
      - field: required
        function: schema
        functionOptions:
          schema:
            type: array
            items:
              type: string
  schemas-required-with-properties:
    description: "Any components/schemas schema with properties also has required array"
    given: $.components.schemas..[?(@ && @.properties)]
    severity: error
    then:
      - field: required
        function: schema
        functionOptions:
          schema:
            type: array
            items:
              type: string
  default-for-responses:
    description: "Responses have default value `$ref: '#/components/responses/Error'`"
    given: $.paths[*][*][responses]
    severity: error
    then:
      field: default
      function: schema
      functionOptions:
        schema:
          $ref: '#/components/responses/Error'
