extends: ["spectral:oas"]
rules:
  operation-description: off
  require-additional-properties-with-properties:
    description: "Any element with properties also has additionalProperties false"
    given: $..[?(@ && @.properties)]
    severity: error
    then:
      - field: additionalProperties
        function: defined
      - field: additionalProperties
        function: falsy
  require-required-with-properties:
    description: "Any element with properties also has required array"
    given: $..[?(@ && @.properties)]
    severity: error
    then:
      - field: required
        function: schema
        functionOptions:
          schema:
            type: array
            items:
              type: string
  require-default-for-responses:
    description: "Responses have default value `$ref: '#/components/responses/Error'`"
    given: $.paths[*][*][responses]
    severity: error
    then:
      field: default
      function: schema
      functionOptions:
        schema:
          $ref: '#/components/responses/Error'
