=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module Ubicloud
  class LoadBalancer
    # Algorithm of the Load Balancer
    attr_accessor :algorithm

    # Networking stack of the Load Balancer (ipv4, ipv6, or dual)
    attr_accessor :stack

    # Destination port for the Load Balancer
    attr_accessor :dst_port

    # Health check endpoint URL
    attr_accessor :health_check_endpoint

    # Health check endpoint protocol
    attr_accessor :health_check_protocol

    # Hostname of the Load Balancer
    attr_accessor :hostname

    # ID of the Load Balancer
    attr_accessor :id

    # Location of the Load Balancer
    attr_accessor :location

    # Name of the Load Balancer
    attr_accessor :name

    # Source port for the Load Balancer
    attr_accessor :src_port

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'algorithm' => :'algorithm',
        :'stack' => :'stack',
        :'dst_port' => :'dst_port',
        :'health_check_endpoint' => :'health_check_endpoint',
        :'health_check_protocol' => :'health_check_protocol',
        :'hostname' => :'hostname',
        :'id' => :'id',
        :'location' => :'location',
        :'name' => :'name',
        :'src_port' => :'src_port'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'algorithm' => :'String',
        :'stack' => :'String',
        :'dst_port' => :'Integer',
        :'health_check_endpoint' => :'String',
        :'health_check_protocol' => :'String',
        :'hostname' => :'String',
        :'id' => :'String',
        :'location' => :'String',
        :'name' => :'String',
        :'src_port' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Ubicloud::LoadBalancer` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Ubicloud::LoadBalancer`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'algorithm')
        self.algorithm = attributes[:'algorithm']
      else
        self.algorithm = nil
      end

      if attributes.key?(:'stack')
        self.stack = attributes[:'stack']
      end

      if attributes.key?(:'dst_port')
        self.dst_port = attributes[:'dst_port']
      else
        self.dst_port = nil
      end

      if attributes.key?(:'health_check_endpoint')
        self.health_check_endpoint = attributes[:'health_check_endpoint']
      else
        self.health_check_endpoint = nil
      end

      if attributes.key?(:'health_check_protocol')
        self.health_check_protocol = attributes[:'health_check_protocol']
      else
        self.health_check_protocol = nil
      end

      if attributes.key?(:'hostname')
        self.hostname = attributes[:'hostname']
      else
        self.hostname = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'src_port')
        self.src_port = attributes[:'src_port']
      else
        self.src_port = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @algorithm.nil?
        invalid_properties.push('invalid value for "algorithm", algorithm cannot be nil.')
      end

      if @dst_port.nil?
        invalid_properties.push('invalid value for "dst_port", dst_port cannot be nil.')
      end

      if @health_check_endpoint.nil?
        invalid_properties.push('invalid value for "health_check_endpoint", health_check_endpoint cannot be nil.')
      end

      if @health_check_protocol.nil?
        invalid_properties.push('invalid value for "health_check_protocol", health_check_protocol cannot be nil.')
      end

      if @hostname.nil?
        invalid_properties.push('invalid value for "hostname", hostname cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      pattern = Regexp.new(/^1b[0-9a-hj-km-np-tv-z]{24}$/)
      if @id !~ pattern
        invalid_properties.push("invalid value for \"id\", must conform to the pattern #{pattern}.")
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @src_port.nil?
        invalid_properties.push('invalid value for "src_port", src_port cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @algorithm.nil?
      return false if @dst_port.nil?
      return false if @health_check_endpoint.nil?
      return false if @health_check_protocol.nil?
      return false if @hostname.nil?
      return false if @id.nil?
      return false if @id !~ Regexp.new(/^1b[0-9a-hj-km-np-tv-z]{24}$/)
      return false if @name.nil?
      return false if @src_port.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] algorithm Value to be assigned
    def algorithm=(algorithm)
      if algorithm.nil?
        fail ArgumentError, 'algorithm cannot be nil'
      end

      @algorithm = algorithm
    end

    # Custom attribute writer method with validation
    # @param [Object] dst_port Value to be assigned
    def dst_port=(dst_port)
      if dst_port.nil?
        fail ArgumentError, 'dst_port cannot be nil'
      end

      @dst_port = dst_port
    end

    # Custom attribute writer method with validation
    # @param [Object] health_check_endpoint Value to be assigned
    def health_check_endpoint=(health_check_endpoint)
      if health_check_endpoint.nil?
        fail ArgumentError, 'health_check_endpoint cannot be nil'
      end

      @health_check_endpoint = health_check_endpoint
    end

    # Custom attribute writer method with validation
    # @param [Object] health_check_protocol Value to be assigned
    def health_check_protocol=(health_check_protocol)
      if health_check_protocol.nil?
        fail ArgumentError, 'health_check_protocol cannot be nil'
      end

      @health_check_protocol = health_check_protocol
    end

    # Custom attribute writer method with validation
    # @param [Object] hostname Value to be assigned
    def hostname=(hostname)
      if hostname.nil?
        fail ArgumentError, 'hostname cannot be nil'
      end

      @hostname = hostname
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      pattern = Regexp.new(/^1b[0-9a-hj-km-np-tv-z]{24}$/)
      if id !~ pattern
        fail ArgumentError, "invalid value for \"id\", must conform to the pattern #{pattern}."
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] src_port Value to be assigned
    def src_port=(src_port)
      if src_port.nil?
        fail ArgumentError, 'src_port cannot be nil'
      end

      @src_port = src_port
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          algorithm == o.algorithm &&
          stack == o.stack &&
          dst_port == o.dst_port &&
          health_check_endpoint == o.health_check_endpoint &&
          health_check_protocol == o.health_check_protocol &&
          hostname == o.hostname &&
          id == o.id &&
          location == o.location &&
          name == o.name &&
          src_port == o.src_port
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [algorithm, stack, dst_port, health_check_endpoint, health_check_protocol, hostname, id, location, name, src_port].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Ubicloud.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
