// Code generated by clover rake terraform:generate. DO NOT EDIT.

package provider

import (
	"os"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"time"
)

// stringListValue converts a scalar string slice (including enum
// string types) into a framework list.
func stringListValue[T ~string](items []T) basetypes.ListValue {
	elems := make([]attr.Value, 0, len(items))
	for _, v := range items {
		elems = append(elems, types.StringValue(string(v)))
	}
	return types.ListValueMust(types.StringType, elems)
}

// derefSlice unwraps the client's optional-slice pointers; nil
// yields the empty slice (an absent list maps to empty, not null).
func derefSlice[T any](p *[]T) []T {
	if p == nil {
		return nil
	}
	return *p
}

// strP boxes a string for optional body fields.
func strP(s string) *string { return &s }

// sliceP boxes a slice for optional body fields.
func sliceP[T any](s []T) *[]T { return &s }

// stringSliceFrom is the write direction: framework list to Go
// slice, cast-ready for enum element types.
func stringSliceFrom[T ~string](list types.List) []T {
	out := make([]T, 0, len(list.Elements()))
	for _, v := range list.Elements() {
		out = append(out, T(v.(types.String).ValueString()))
	}
	return out
}

// envDuration lets out-of-process harnesses tune wait loops to
// memory speed (UBICLOUD_<RESOURCE>_* variables).
func envDuration(name string, fallback time.Duration) time.Duration {
	if v := os.Getenv(name); v != "" {
		if d, err := time.ParseDuration(v); err == nil {
			return d
		}
	}
	return fallback
}


// The API's identity contract is two-part, Azure-style: the user
// supplies the name a priori - it is the idempotency key within its
// project/location scope - while the system id exists only in
// responses, after commit. The engine therefore reads, deletes, and
// imports by the scoped name, and treats a same-name row as this
// configuration's claim on that identity.

// upgradeStateIdentity: schema-version bumps whose wire change is
// decode-tolerant (the populated timeouts type reads every relic
// shape) need no field surgery - the prior state, decoded under the
// current schema as PriorSchema, is the upgraded state.
func upgradeStateIdentity(ctx context.Context, req resource.UpgradeStateRequest, resp *resource.UpgradeStateResponse) {
	resp.State.Raw = req.State.Raw
}

// crudDatasourceRead: fetch and map for a data source. Every
// non-200 - 404 included - is an error: a data source has no state
// to remove, only a lookup that did or did not resolve.
func crudDatasourceRead[M any, A any](ctx context.Context, resp *datasource.ReadResponse, human string,
	logID func(*M) string, state *M,
	details func(*M) (*apiEnvelope[A], error),
	setState func(context.Context, *A, *M) diag.Diagnostics) {
	tflog.Debug(ctx, fmt.Sprintf("Reading %s: %s", human, logID(state)))
	apiResp, err := details(state)
	if d := apiGuard("reading", human, logID(state), apiResp, err); d.HasError() {
		resp.Diagnostics.Append(d...)
		return
	}
	resp.Diagnostics.Append(setState(ctx, apiResp.JSON200, state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// One update verb as data: changed says whether the plan touches its
// attributes; run performs it, mutating state as progress commits so
// a later failure persists what already took server-side.
type verbStep[M any] struct {
	name    string
	changed func(plan, state *M) bool
	run     func(plan, state *M) diag.Diagnostics
}

// crudUpdate: dispatch the verb table in declared order. On any
// step's failure, persist state first - progress that committed
// (a rename, a merged config) must survive the error - then report.
// finish owns the post-dispatch re-read and persistence.
func crudUpdate[M any](ctx context.Context, resp *resource.UpdateResponse, human string,
	logID func(*M) string, plan, state *M, steps []verbStep[M], finish func(*M)) {
	for _, step := range steps {
		if !step.changed(plan, state) {
			continue
		}
		tflog.Debug(ctx, fmt.Sprintf("Updating %s (%s): %s", human, step.name, logID(state)))
		d := step.run(plan, state)
		if d.HasError() {
			resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
			resp.Diagnostics.Append(d...)
			return
		}
		resp.Diagnostics.Append(d...)
	}
	finish(state)
}

// crudCreate: POST the claim. A clean rejection fails - the server
// named its reason and no adoption is implied. An ambiguous outcome
// (transport error, or a 200 whose body was lost) reconciles by the
// scoped name: the name is this configuration's claim, so a row
// answering to it is the create's result; absence means the create
// truly failed. finish owns the resource's post-create tail
// (convergence wait, remap, state persistence).
func crudCreate[M any, C any, D any](ctx context.Context, resp *resource.CreateResponse, human string,
	logID func(*M) string, state *M,
	create func(*M) (*apiEnvelope[C], error),
	probe func(*M) (*apiEnvelope[D], error),
	setFromCreate func(context.Context, *C, *M) diag.Diagnostics,
	setFromProbe func(context.Context, *D, *M) diag.Diagnostics,
	finish func(*M)) {
	tflog.Debug(ctx, fmt.Sprintf("Creating %s: %s", human, logID(state)))
	reconcile := func(cause string) bool {
		pr, perr := probe(state)
		if perr != nil || pr.StatusCode() != http.StatusOK || pr.JSON200 == nil {
			return false
		}
		tflog.Warn(ctx, fmt.Sprintf("%s create was ambiguous (%s); reconciled by name: %s", human, cause, logID(state)))
		resp.Diagnostics.Append(setFromProbe(ctx, pr.JSON200, state)...)
		return !resp.Diagnostics.HasError()
	}
	apiResp, err := create(state)
	if err != nil {
		if reconcile(err.Error()) {
			finish(state)
			return
		}
		resp.Diagnostics.Append(apiFailErr("creating", human, logID(state), err)...)
		return
	}
	if apiResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.Append(apiFailStatus("creating", human, logID(state), apiResp.Status(), apiResp.Body)...)
		return
	}
	if apiResp.JSON200 == nil {
		if reconcile("empty 200 body") {
			finish(state)
			return
		}
		resp.Diagnostics.AddError(
			fmt.Sprintf("Empty response creating %s", human),
			fmt.Sprintf("the API returned no %s body and no row answers to the name: %s", human, logID(state)))
		return
	}
	resp.Diagnostics.Append(setFromCreate(ctx, apiResp.JSON200, state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	finish(state)
}

// apiFailErr, apiFailStatus, apiFailEmpty: one diagnostic grammar
// for every plane's failed API exchange. action reads as a gerund
// phrase ("reading", "deleting", "applying rename to"); the detail
// carries status, identifier, and raw body so the operator sees
// what the API saw.
func apiFailErr(action, human, id string, err error) diag.Diagnostics {
	var d diag.Diagnostics
	d.AddError(fmt.Sprintf("Error %s %s: %s", action, human, id), err.Error())
	return d
}

func apiFailStatus(action, human, id, status string, body []byte) diag.Diagnostics {
	var d diag.Diagnostics
	d.AddError(
		fmt.Sprintf("Unexpected HTTP status code %s %s", action, human),
		fmt.Sprintf("Received %s for %s: %s. Details: %s", status, human, id, body))
	return d
}

func apiFailEmpty(action, human, id string) diag.Diagnostics {
	var d diag.Diagnostics
	d.AddError(
		fmt.Sprintf("Empty response %s %s", action, human),
		fmt.Sprintf("the API returned no %s body: %s", human, id))
	return d
}

// apiGuard: the composed three-way check - transport error,
// non-200, bodyless 200 - for envelope calls whose only special
// case is total success. Callers with special statuses (a Read's
// 404-remove, a Create's reconciliation) test those first and use
// the constructors piecewise.
func apiGuard[T any](action, human, id string, apiResp *apiEnvelope[T], err error) diag.Diagnostics {
	switch {
	case err != nil:
		return apiFailErr(action, human, id, err)
	case apiResp.StatusCode() != http.StatusOK:
		return apiFailStatus(action, human, id, apiResp.Status(), apiResp.Body)
	case apiResp.JSON200 == nil:
		return apiFailEmpty(action, human, id)
	}
	return nil
}

// crudRead: fetch details, drop from state on 404 so the next plan
// converges, fail closed on anything else, map, and set state.
func crudRead[M any, A any](ctx context.Context, resp *resource.ReadResponse, human string,
	logID func(*M) string, state *M,
	details func(*M) (*apiEnvelope[A], error),
	setState func(context.Context, *A, *M) diag.Diagnostics) {
	tflog.Debug(ctx, fmt.Sprintf("Reading %s: %s", human, logID(state)))
	apiResp, err := details(state)
	if err != nil {
		resp.Diagnostics.Append(apiFailErr("reading", human, logID(state), err)...)
		return
	}
	if apiResp.StatusCode() == http.StatusNotFound {
		tflog.Debug(ctx, fmt.Sprintf("%s not found, removing from state: %s", human, logID(state)))
		resp.State.RemoveResource(ctx)
		return
	}
	if d := apiGuard("reading", human, logID(state), apiResp, nil); d.HasError() {
		resp.Diagnostics.Append(d...)
		return
	}
	resp.Diagnostics.Append(setState(ctx, apiResp.JSON200, state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// crudDelete: issue the delete (404 is success - the claim is
// already released), then optionally block until the name is free so
// dependents can recreate immediately.
func crudDelete[M any](ctx context.Context, resp *resource.DeleteResponse, human string,
	logID func(*M) string, state *M,
	del func(*M) (int, string, []byte, error),
	wait func(*M) diag.Diagnostics) {
	tflog.Debug(ctx, fmt.Sprintf("Deleting %s: %s", human, logID(state)))
	code, status, body, err := del(state)
	if err != nil {
		resp.Diagnostics.Append(apiFailErr("deleting", human, logID(state), err)...)
		return
	}
	if code != http.StatusNoContent && code != http.StatusNotFound {
		resp.Diagnostics.Append(apiFailStatus("deleting", human, logID(state), status, body)...)
		return
	}
	if wait != nil {
		resp.Diagnostics.Append(wait(state)...)
	}
}

// crudImport: the import id is the comma-joined scoped name (or the
// resource's declared key attributes, in order).
func crudImport(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse, attrs []string) {
	idParts := strings.Split(req.ID, ",")
	bad := len(idParts) != len(attrs)
	for _, p := range idParts {
		bad = bad || p == ""
	}
	if bad {
		resp.Diagnostics.AddError(
			"Unexpected Import Identifier",
			fmt.Sprintf("Expected import identifier with format: %s. Got: %q", strings.Join(attrs, ","), req.ID))
		return
	}
	for i, a := range attrs {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root(a), idParts[i])...)
	}
}

// apiEnvelope carries what call sites consume: the raw body always,
// the parsed payload on a JSON 200. Generated guards test JSON200
// for presence.
type apiEnvelope[T any] struct {
	code    int
	status  string
	Body    []byte
	JSON200 *T
}

func (e *apiEnvelope[T]) StatusCode() int { return e.code }
func (e *apiEnvelope[T]) Status() string  { return e.status }

// apiCall is the whole HTTP client: build, authorize, do, decode.
// Optionality and shapes are the generator's business upstream;
// nothing here inspects types beyond JSON.
func apiCall[T any](ctx context.Context, uc *UbicloudClient, method, path string, body any) (*apiEnvelope[T], error) {
	var buf io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("encoding %s %s body: %w", method, path, err)
		}
		buf = bytes.NewReader(b)
	}
	req, err := http.NewRequestWithContext(ctx, method, uc.endpoint+path, buf)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+uc.token)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	env := &apiEnvelope[T]{code: resp.StatusCode, status: resp.Status, Body: raw}
	if resp.StatusCode == http.StatusOK {
		var parsed T
		if json.Unmarshal(raw, &parsed) == nil && len(bytes.TrimSpace(raw)) > 0 {
			env.JSON200 = &parsed
		}
	}
	return env, nil
}
