---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ubicsi-provisioner
  namespace: ubicsi
subjects:
  - kind: ServiceAccount
    name: ubicsi-provisioner
    namespace: ubicsi
roleRef:
  kind: Role
  name: ubicsi-provisioner
  apiGroup: rbac.authorization.k8s.io
