# frozen_string_literal: true

module TerraformGenerator
  # The declaration half of emission: models, schema functions,
  # attr-type tables, API component and body structs, the generic
  # transport, and provider registration - Go that is data-shaped,
  # rendered directly from the derived planes. Control-flow Go (CRUD
  # methods, verb dispatch, waits) stays in the ERB templates; both
  # halves live under Emit.
  # Emits, per definition, the in-package declaration files: models,
  # schema functions, and attr-type tables (nested conformance via
  # framework-native types.Object), API component structs with a
  # request-path helper, and the one-time generic HTTP runtime.
  #
  # The schema renderer walks the SAME hash Schema.spec_for builds for
  # the JSON plane - one derivation, two renderers - so schema_diff's
  # guarantees transfer.
  module Emit
    module Declarations
      module_function

      GO_SCALAR = {"string" => "types.String", "integer" => "types.Int64",
                   "boolean" => "types.Bool", "number" => "types.Float64",
                   "map" => "types.Map", "string_list" => "types.List"}.freeze

      JSON_GO = {"string" => "string", "integer" => "int", "boolean" => "bool",
                 "number" => "float64"}.freeze

      def model_name(definition, kind) = "#{Emit.go_field(definition.name.to_s)}#{kind.to_s.capitalize}Model".sub(/\A./) { it.downcase }
      def struct_name(component) = "api#{component}"
      def attr_types_fn(definition, a, kind) = "#{Emit.go_field(definition.name.to_s)}#{kind.to_s.capitalize}#{a.path_camel}AttrTypes".sub(/\A./) { it.downcase }

      # --- models + attr-type tables + schema functions, per kind ---

      def gen_source(definition)
        out = +"// Code generated by clover rake terraform:generate. DO NOT EDIT.\n\npackage provider\n\n"
        out << imports_block(definition)
        definition.emitted_kinds.each do |kind|
          attrs, keys = kind_attrs(definition, kind)
          out << model_struct(definition, kind, attrs, keys)
        end
        definition.emitted_kinds.each do |kind|
          attrs, = kind_attrs(definition, kind)
          attrs.flat_map { collect_nested(it) }.uniq(&:path_camel)
            .each { out << attr_types(definition, it, kind) }
        end
        definition.emitted_kinds.each do |kind|
          out << schema_function(definition, kind)
        end
        out
      end

      def kind_attrs(definition, kind)
        if kind == :resource
          ctx = Emit::ResourceContext.new(definition)
          keys = ctx.key_pairs.map { _2.to_s }
          body_only = ctx.create_body_attributes.reject { |b| ctx.read_mapper.attrs.any? { it.tf_name == b.tf_name } || keys.include?(b.tf_name) }
          [ctx.read_mapper.attrs + body_only, keys]
        else
          attrs, _, key_pairs = Reflection.attributes_for(definition)
          [attrs, key_pairs.map { _2.to_s }]
        end
      end

      def model_fields(definition, kind, attrs, keys)
        fields = {}
        attrs.each { fields[it.tf_name] = it.nested ? "types.List" : GO_SCALAR.fetch(it.json_type) }
        keys.each { fields[it] ||= "types.String" }
        definition.flagged(:inject, kind:).each do |path|
          spec = definition.attr_options_for(path, kind)[:inject]
          fields[path] = GO_SCALAR.fetch(spec[:type].to_s)
        end
        attrs.each do |a|
          alias_tf = a.options[:also_tf]
          fields[alias_tf.to_s] = fields[a.tf_name] if alias_tf
        end
        fields
      end

      def model_struct(definition, kind, attrs, keys)
        fields = model_fields(definition, kind, attrs, keys)
        lines = fields.sort.map { |tf, t| "\t#{Emit.go_field(tf)} #{t} `tfsdk:\"#{tf}\"`" }
        if kind == :resource && Schema.spec_for(definition, kind)["schema"]["blocks"]&.any?
          lines << "\tTimeouts timeouts.Value `tfsdk:\"timeouts\"`"
        end
        "type #{model_name(definition, kind)} struct {\n#{lines.join("\n")}\n}\n\n"
      end

      def collect_nested(a)
        return [] unless a.nested
        [a] + a.nested.flat_map { collect_nested(it) }
      end

      def attr_types(definition, a, kind)
        lines = a.nested.map do |n|
          t = n.nested ? "types.ListType{ElemType: types.ObjectType{AttrTypes: #{attr_types_fn(definition, n, kind)}()}}" : "#{GO_SCALAR.fetch(n.json_type)}Type"
          "\t\t\"#{n.tf_name}\": #{n.nested ? t : go_attr_type(n)},"
        end
        <<-GO
func #{attr_types_fn(definition, a, kind)}() map[string]attr.Type {
	return map[string]attr.Type{
#{lines.join("
")}
	}
}

        GO
      end

      def go_attr_type(n)
        {"string" => "types.StringType", "integer" => "types.Int64Type",
         "boolean" => "types.BoolType", "number" => "types.Float64Type",
         "map" => "types.MapType{ElemType: types.StringType}",
         "string_list" => "types.ListType{ElemType: types.StringType}"}.fetch(n.json_type)
      end

      # --- schema renderer: walks Schema.spec_for's hash into Go ---
      # Heredocs are deliberately not indent-corrected: bodies are the
      # emitted text verbatim - column zero, real tabs - so the source
      # reads as the output it produces.

      SCHEMA_ATTR = {"string" => "StringAttribute", "int64" => "Int64Attribute",
                     "bool" => "BoolAttribute", "float64" => "Float64Attribute",
                     "map" => "MapAttribute", "list" => "ListAttribute",
                     "list_nested" => "ListNestedAttribute"}.freeze

      def schema_function(definition, kind)
        spec = Schema.spec_for(definition, kind)
        pkg = (kind == :resource) ? "schema" : "dschema"
        fn = "#{Emit.go_field(definition.name.to_s)}#{(kind == :resource) ? "Resource" : "DataSource"}Schema"
        body = spec["schema"]["attributes"].map { attribute_literal(definition, it, pkg, indent: 3) }.join("\n")
        blocks = blocks_literal(spec["schema"]["blocks"], pkg)
        upgradeable = kind == :resource && spec["schema"]["blocks"]&.any?
        version = upgradeable ? "\n\tVersion: 1," : ""
        <<-GO
func #{fn}(ctx context.Context) #{pkg}.Schema {
	return #{pkg}.Schema{#{version}
		Attributes: map[string]#{pkg}.Attribute{
#{body}
		},#{blocks}
	}
}

        GO
      end

      # The timeouts block, populated to the golden's declared
      # attributes. Schema Version 1 marks the wire change; the
      # engine's identity upgrader migrates relics, since the populated
      # type decodes every shape the bare era wrote.
      def timeouts_attr_types(blocks)
        b = blocks.find { it["name"] == "timeouts" }
        names = b["single_nested"]["attributes"].map { it["name"] }
        "map[string]attr.Type{" + names.map { %("#{it}": types.StringType) }.join(", ") + "}"
      end

      def blocks_literal(blocks, pkg, bare: false)
        return "" if blocks.nil? || blocks.empty?
        b = blocks.find { it["name"] == "timeouts" } or
          raise "block shape not yet supported (extend when first needed)"
        attrs = b["single_nested"]["attributes"].map { attribute_literal(nil, it, pkg, indent: 4) }.join("\n")
        at = bare ? "timeouts.Value{}.AttributeTypes(ctx)" : timeouts_attr_types(blocks)
        <<-GO.chomp

		Blocks: map[string]#{pkg}.Block{
			"timeouts": #{pkg}.SingleNestedBlock{
				CustomType: timeouts.Type{ObjectType: types.ObjectType{AttrTypes: #{at}}},
				Attributes: map[string]#{pkg}.Attribute{
#{attrs}
				},
			},
		},
        GO
      end

      def attribute_literal(definition, entry, pkg, indent:)
        name = entry["name"]
        type = entry.keys.reject { it == "name" }.first
        b = entry[type]
        pad = "\t" * indent
        fields = []
        cls = b["computed_optional_required"]
        fields << "Required: true" if cls == "required"
        fields << "Optional: true" if %w[optional computed_optional].include?(cls)
        fields << "Computed: true" if %w[computed computed_optional].include?(cls)
        fields << "Sensitive: true" if b["sensitive"]
        fields << "Description: #{b["description"].inspect}" if b["description"]
        fields << "MarkdownDescription: #{b["description"].inspect}" if b["description"]
        fields << "ElementType: types.StringType" if b["element_type"]
        if (pm = b["plan_modifiers"])
          exprs = pm.map { it["custom"]["schema_definition"] }
          fields << "PlanModifiers: []planmodifier.#{modifier_iface(type)}{#{exprs.join(", ")}}"
        end
        if (vals = b["validators"])
          exprs = vals.map { it["custom"]["schema_definition"] }
          fields << "Validators: []validator.#{modifier_iface(type)}{#{exprs.join(", ")}}"
        end
        if type == "list_nested"
          nested = b["nested_object"]["attributes"].map { attribute_literal(definition, it, pkg, indent: indent + 3) }.join("\n")
          fields << "NestedObject: #{pkg}.NestedAttributeObject{\n#{pad}\tAttributes: map[string]#{pkg}.Attribute{\n#{nested}\n#{pad}\t},\n#{pad}}"
        end
        "#{pad}\"#{name}\": #{pkg}.#{SCHEMA_ATTR.fetch(type)}{\n#{fields.map { "#{pad}\t#{it}," }.join("\n")}\n#{pad}},"
      end

      def modifier_iface(spec_type)
        {"string" => "String", "int64" => "Int64", "bool" => "Bool",
         "float64" => "Float64", "map" => "Map", "list" => "List",
         "list_nested" => "List"}.fetch(spec_type)
      end

      def imports_block(definition)
        spec_imports = definition.emitted_kinds.flat_map do |k|
          collect_imports(Schema.spec_for(definition, k)["schema"]["attributes"])
        end.uniq.sort
        lines = [
          "\t\"context\"\n",
          "\n",
          (has_nested?(definition) ? "\t\"github.com/hashicorp/terraform-plugin-framework/attr\"\n" : nil),
          (definition.emitted_kinds.include?(:datasource) ? "\tdschema \"github.com/hashicorp/terraform-plugin-framework/datasource/schema\"\n" : nil),
          (definition.emitted_kinds.include?(:resource) ? "\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema\"\n" : nil),
          "\t\"github.com/hashicorp/terraform-plugin-framework/schema/validator\"\n",
          "\t\"github.com/hashicorp/terraform-plugin-framework/types\"\n",
          ((definition.emitted_kinds.include?(:resource) && Schema.spec_for(definition, :resource)["schema"]["blocks"]&.any?) ?
            "\ttimeouts \"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts\"\n" : nil),
          ((definition.emitted_kinds.include?(:resource) && Schema.spec_for(definition, :resource)["schema"]["blocks"]&.any?) ?
            "\t\"github.com/hashicorp/terraform-plugin-framework/attr\"\n" : nil),
        ].compact
        lines += spec_imports.map { "\t\"#{it}\"\n" }
        pm = spec_imports.any? { it.include?("planmodifier") }
        lines.unshift("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier\"\n") if pm
        "import (\n#{lines.uniq.join})\n\n"
      end

      def has_nested?(definition)
        definition.emitted_kinds.any? { |k| kind_attrs(definition, k)[0].any?(&:nested) }
      end

      def collect_imports(attrs)
        attrs.flat_map do |entry|
          type = entry.keys.reject { it == "name" }.first
          b = entry[type]
          paths = (Array(b["plan_modifiers"]) + Array(b["validators"]))
            .flat_map { it["custom"]["imports"].map { |i| i["path"] } }
          paths += collect_imports(b["nested_object"]["attributes"]) if type == "list_nested"
          paths
        end
      end

      # --- client slice: component structs + path helper ---

      def client_source(definition)
        ctx = Emit::ResourceContext.new(definition) if definition.emitted_kinds.include?(:resource)
        out = +"// Code generated by clover rake terraform:generate. DO NOT EDIT.\n\npackage provider\n\n"
        out << body_struct(definition, ctx) if ctx
        out << verb_structs(definition) if ctx
        out
      end

      # Kind omits are TF-plane; the JSON structs carry the union of
      # every field any kind maps for a component.
      def union!(acc, name, attrs)
        existing = acc[name] || []
        keys = existing.map(&:key)
        acc[name] = existing + attrs.reject { keys.include?(it.key) }
      end

      def collect_components(definition, ctx, acc)
        ctx.response_mappers.each do |m|
          union!(acc, m.client_type, m.attrs)
          m.attrs.select(&:nested).each { collect_nested_components(it, acc) }
        end
      end

      def collect_nested_components(a, acc)
        union!(acc, a.client_type, a.nested)
        a.nested.select(&:nested).each { collect_nested_components(it, acc) }
      end

      def go_json_type(a)
        return "[]#{struct_name(a.client_type)}" if a.nested
        return "time.Time" if a.format == "date-time"
        return "[]string" if a.json_type == "string_list"
        return "map[string]string" if a.json_type == "map"
        JSON_GO.fetch(a.json_type, "string")  # enums decode as their base string
      end

      # Verb-plane structs the generic component walk does not reach:
      # the tombstone patch body, and the read components of tombstone /
      # exclusive verbs (config union, upgrade status).
      def verb_structs(definition)
        out = +""
        definition.update_verbs.each do |v|
          unless v[:tombstones] || v[:exclusive]
            op = Reflection.verb_operation(definition, v)
            Reflection.resolve_verb_attrs!(v, op)
            fields = Reflection.verb_body_attributes(definition, v, op).map do |a|
              go_t = JSON_GO.fetch(a.json_type, "string")
              go_t = "*[]string" if a.json_type == "string_list"
              go_t = "*#{go_t}" if a.pointer && a.json_type != "string_list"
              "\t#{a.api_go_field} #{go_t} `json:\"#{a.key},omitempty\"`"
            end
            out << "type api#{Emit.go_field(definition.name.to_s)}#{Emit.go_field(v[:name])}Body struct {\n#{fields.join("\n")}\n}\n\n"
          end
          if v[:tombstones]
            out << "type api#{Emit.go_field(definition.name.to_s)}PatchConfig struct {\n" \
                   "\tPgConfig        map[string]*string  `json:\"pg_config\"`\n" \
                   "\tPgbouncerConfig *map[string]*string `json:\"pgbouncer_config,omitempty\"`\n}\n\n"
            out << "type apiPostgresConfig struct {\n" \
                   "\tPgConfig        map[string]string `json:\"pg_config\"`\n" \
                   "\tPgbouncerConfig map[string]string `json:\"pgbouncer_config\"`\n}\n\n"
          end
          if v[:exclusive]
            out << "type apiPostgresUpgradeStatus struct {\n" \
                   "\tCurrentVersion string `json:\"current_version\"`\n" \
                   "\tTargetVersion  string `json:\"target_version\"`\n" \
                   "\tUpgradeStatus  string `json:\"upgrade_status\"`\n}\n\n"
          end
        end
        out
      end

      def component_struct(name, attrs)
        lines = attrs.map do |a|
          go_t = go_json_type(a)
          go_t = "*#{go_t}" if a.pointer && !a.nested
          "\t#{a.api_go_field} #{go_t} `json:\"#{a.key},omitempty\"`"
        end
        "type #{struct_name(name)} struct {\n#{lines.join("\n")}\n}\n\n"
      end

      def body_struct(definition, ctx)
        lines = ctx.create_body_attributes.map do |a|
          go_t = JSON_GO.fetch(a.json_type, "string")
          go_t = "*#{go_t}" if a.pointer
          "\t#{a.api_go_field} #{go_t} `json:\"#{a.key}#{",omitempty" if a.pointer}\"`"
        end
        "type api#{Emit.go_field(definition.name.to_s)}CreateBody struct {\n#{lines.join("\n")}\n}\n\n"
      end

      def path_helper(definition, ctx)
        ""  # paths are inlined at call sites via Sprintf; no helper needed
      end

      # Registration and wire-type registry: adding a resource touches
      # zero hand Go, and the wire-golden test iterates the registry so a
      # new resource cannot ship ungoldened.
      def provider_source
        names = TerraformGenerator.resources.keys.sort
        res, ds, wire = [], [], []
        names.each do |n|
          d = TerraformGenerator[n]
          c = Emit.go_field(n.to_s)
          if d.emitted_kinds.include?(:resource)
            res << "\t\tNew#{c}Resource,"
            wire << "\t\t\"resource_#{n}\": #{c}ResourceSchema(ctx).Type().TerraformType(ctx).String(),"
          end
          if d.emitted_kinds.include?(:datasource)
            ds << "\t\tNew#{c}DataSource,"
            wire << "\t\t\"datasource_#{n}\": #{c}DataSourceSchema(ctx).Type().TerraformType(ctx).String(),"
          end
        end
        <<-GO
// Code generated by clover rake terraform:generate. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

func generatedResources() []func() resource.Resource {
	return []func() resource.Resource{
#{res.join("
")}
	}
}

func generatedDataSources() []func() datasource.DataSource {
	return []func() datasource.DataSource{
#{ds.join("
")}
	}
}

// generatedWireTypes feeds TestWireGoldens; keys must stay golden.
func generatedWireTypes(ctx context.Context) map[string]string {
	return map[string]string{
#{wire.join("
")}
	}
}
        GO
      end

      # Docs examples derive so they cannot drift from the schema:
      # required args only, var-block style; a required parent reference
      # pulls its parent resource in, depth one, so examples stay
      # copy-paste runnable.
      def example_sources(definition)
        out = {}
        base = File.join(Emit.provider_repo, "examples")
        if definition.emitted_kinds.include?(:resource)
          out[File.join(base, "resources", "ubicloud_#{definition.name}", "resource.tf")] =
            resource_example(definition)
        end
        if definition.emitted_kinds.include?(:datasource)
          out[File.join(base, "data-sources", "ubicloud_#{definition.name}", "data-source.tf")] =
            datasource_example(definition)
        end
        out
      end

      EXAMPLE_VARS = <<-TF
variable "project_id" {
  description = "Ubicloud project"
  type        = string
  default     = "pj01qy4sty1j7nycv8hfqmgy6t"
}

variable "location" {
  description = "Ubicloud location"
  type        = string
  default     = "eu-central-h1"
}

      TF

      def example_value(definition, name, parents)
        case name
        when "project_id" then "var.project_id"
        when "location" then "var.location"
        when "name" then "\"example-#{definition.name.to_s.tr("_", "-")}\""
        when "cidr" then "\"10.0.0.0/24\""
        when "size" then "\"standard-2\""
        when "id", /_id\z/ then "\"#{definition.name.to_s[0, 2]}01qy4sty1j7nycv8hfqmgy6t\""
        when "public_key" then "\"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEXAMPLEexampleEXAMPLEexampleEXAMPLEexampleEXAM user@example\""
        when /\A(\w+)_reference\z/
          parent = TerraformGenerator[$1.to_sym]
          parents << parent
          "ubicloud_#{parent.name}.example.name"
        else
          raise "#{definition.name}: example needs a value rule for required #{name}"
        end
      end

      def required_args(definition)
        TerraformGenerator::Schema.spec_for(definition, :resource)["schema"]["attributes"]
          .filter_map do |a|
            type = a.keys.reject { it == "name" }.first
            a["name"] if a[type]["computed_optional_required"] == "required"
          end
      end

      def resource_block(definition, label, parents)
        args = required_args(definition).map do |n|
          "  #{n} = #{example_value(definition, n, parents)}"
        end
        "resource \"ubicloud_#{definition.name}\" \"#{label}\" {\n#{args.join("\n")}\n}\n"
      end

      def resource_example(definition)
        parents = []
        body = resource_block(definition, "example", parents)
        parent_bodies = parents.uniq.map { resource_block(it, "example", []) + "\n" }.join
        EXAMPLE_VARS + parent_bodies + body
      end

      def datasource_example(definition)
        _, _, key_pairs = TerraformGenerator::Reflection.attributes_for(definition)
        parents = []
        args = key_pairs.map do |_, attr|
          "  #{attr} = #{example_value(definition, attr.to_s, parents)}"
        end
        pb = parents.uniq.map { resource_block(it, "example", []) + "\n" }.join
        EXAMPLE_VARS + pb +
          "data \"ubicloud_#{definition.name}\" \"example\" {\n#{args.join("\n")}\n}\n"
      end

      # path => rendered content for this definition's declaration files
      # plus the shared plane (component union, registration, runtime,
      # examples); terraform:check byte-compares committed files against
      # exactly this map.
      def sources(definition)
        base = File.join(Emit.provider_repo, "internal", "provider")
        example_sources(definition).merge(
          File.join(base, "provider_gen.go") => provider_source,
          File.join(base, "api_components_gen.go") => shared_components_source,
          File.join(base, "#{definition.name}_gen.go") => gen_source(definition),
          File.join(base, "#{definition.name}_client_gen.go") => client_source(definition),
        )
      end

      # Components are API-global (private_subnet nests firewalls nests
      # rules); one shared file owns every struct across flagged
      # definitions, recomputed deterministically on any generate.
      def shared_components_source
        components = {}
        TerraformGenerator.resources.each_key do |name|
          d = TerraformGenerator[name]
          collect_components(d, Emit::ResourceContext.new(d), components) if d.emitted_kinds.include?(:resource)
          if d.emitted_kinds.include?(:datasource)
            attrs, = kind_attrs(d, :datasource)
            ctx = Emit::DatasourceContext.new(d)
            union!(components, ctx.details_component, attrs)
            attrs.select(&:nested).each { collect_nested_components(it, components) }
          end
        end
        needs_time = components.values.flatten.any? { it.format == "date-time" }
        out = +"// Code generated by clover rake terraform:generate. DO NOT EDIT.\n\npackage provider\n\n"
        out << "import \"time\"\n\n" if needs_time
        out << components.sort.map { |n, a| component_struct(n, a) }.join
      end
    end
  end
end
