# frozen_string_literal: true

require "yaml"

# config/instance_availability.yml holds one key per provider, and each is
# generated by its own script from that provider's API. Writes go through here
# so regenerating one provider cannot drop another's data.
class InstanceAvailabilityFile
  def self.merge_providers(path, providers)
    data = File.file?(path) ? YAML.load_file(path) : {}
    data["providers"] = (data["providers"] || {}).merge(providers).sort.to_h
    File.write(path, YAML.dump(data))
    data
  end
end
