=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

# Common files
require 'ubicloud-sdk/api_client'
require 'ubicloud-sdk/api_error'
require 'ubicloud-sdk/version'
require 'ubicloud-sdk/configuration'

# Models
require 'ubicloud-sdk/models/action_location_firewall_attach_subnet_request'
require 'ubicloud-sdk/models/action_location_firewall_detach_subnet_request'
require 'ubicloud-sdk/models/attach_vm_location_load_balancer_request'
require 'ubicloud-sdk/models/connect_private_subnet_request'
require 'ubicloud-sdk/models/create_firewall_request'
require 'ubicloud-sdk/models/create_firewall_rule_request'
require 'ubicloud-sdk/models/create_load_balancer_request'
require 'ubicloud-sdk/models/create_location_firewall_request'
require 'ubicloud-sdk/models/create_location_postgres_firewall_rule_request'
require 'ubicloud-sdk/models/create_location_postgres_metric_destination_request'
require 'ubicloud-sdk/models/create_postgres_database_request'
require 'ubicloud-sdk/models/create_private_subnet_request'
require 'ubicloud-sdk/models/create_project_request'
require 'ubicloud-sdk/models/create_vm_request'
require 'ubicloud-sdk/models/detach_vm_location_load_balancer_request'
require 'ubicloud-sdk/models/error'
require 'ubicloud-sdk/models/error_error'
require 'ubicloud-sdk/models/firewall'
require 'ubicloud-sdk/models/firewall_rule'
require 'ubicloud-sdk/models/get_firewall200_response'
require 'ubicloud-sdk/models/get_load_balancer200_response'
require 'ubicloud-sdk/models/get_location_firewall_details200_response'
require 'ubicloud-sdk/models/get_object_info200_response'
require 'ubicloud-sdk/models/get_postgres_database_details200_response'
require 'ubicloud-sdk/models/get_vm_details200_response'
require 'ubicloud-sdk/models/list_load_balancers200_response'
require 'ubicloud-sdk/models/list_location_postgres_databases200_response'
require 'ubicloud-sdk/models/list_location_postgres_firewall_rules200_response'
require 'ubicloud-sdk/models/list_location_private_subnets200_response'
require 'ubicloud-sdk/models/list_location_vms200_response'
require 'ubicloud-sdk/models/list_projects200_response'
require 'ubicloud-sdk/models/load_balancer'
require 'ubicloud-sdk/models/login200_response'
require 'ubicloud-sdk/models/login_request'
require 'ubicloud-sdk/models/nic'
require 'ubicloud-sdk/models/patch_location_load_balancer_request'
require 'ubicloud-sdk/models/postgres_database'
require 'ubicloud-sdk/models/postgres_firewall_rule'
require 'ubicloud-sdk/models/private_subnet'
require 'ubicloud-sdk/models/project'
require 'ubicloud-sdk/models/reset_superuser_password_request'
require 'ubicloud-sdk/models/restore_postgres_database_request'
require 'ubicloud-sdk/models/vm'

# APIs
require 'ubicloud-sdk/api/firewall_api'
require 'ubicloud-sdk/api/firewall_rule_api'
require 'ubicloud-sdk/api/load_balancer_api'
require 'ubicloud-sdk/api/login_api'
require 'ubicloud-sdk/api/postgres_database_api'
require 'ubicloud-sdk/api/postgres_firewall_rule_api'
require 'ubicloud-sdk/api/postgres_metric_destination_api'
require 'ubicloud-sdk/api/private_subnet_api'
require 'ubicloud-sdk/api/project_api'
require 'ubicloud-sdk/api/virtual_machine_api'

module Ubicloud
  class << self
    # Customize default settings for the SDK using block.
    #   Ubicloud.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
