---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ubicsi-provisioner
subjects:
  - kind: ServiceAccount
    name: ubicsi-provisioner
    namespace: ubicsi
roleRef:
  kind: ClusterRole
  name: ubicsi-provisioner
  apiGroup: rbac.authorization.k8s.io
