=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Ubicloud::FirewallApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FirewallApi' do
  before do
    # run before each test
    @api_instance = Ubicloud::FirewallApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FirewallApi' do
    it 'should create an instance of FirewallApi' do
      expect(@api_instance).to be_instance_of(Ubicloud::FirewallApi)
    end
  end

  # unit tests for action_location_firewall_attach_subnet
  # Attach a subnet to firewall
  # @param location The Ubicloud location/region
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param action_location_firewall_attach_subnet_request 
  # @param [Hash] opts the optional parameters
  # @return [GetLocationFirewallDetails200Response]
  describe 'action_location_firewall_attach_subnet test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for action_location_firewall_detach_subnet
  # Detach a subnet from firewall
  # @param location The Ubicloud location/region
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param action_location_firewall_detach_subnet_request 
  # @param [Hash] opts the optional parameters
  # @return [GetLocationFirewallDetails200Response]
  describe 'action_location_firewall_detach_subnet test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_firewall
  # Create a new firewall
  # @param project_id ID of the project
  # @param create_firewall_request 
  # @param [Hash] opts the optional parameters
  # @return [Firewall]
  describe 'create_firewall test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_location_firewall
  # Create a new firewall
  # @param location The Ubicloud location/region
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param create_location_firewall_request 
  # @param [Hash] opts the optional parameters
  # @return [Firewall]
  describe 'create_location_firewall test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_firewall
  # Delete a specific firewall
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_firewall test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_location_firewall
  # Delete a specific firewall
  # @param location The Ubicloud location/region
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_location_firewall test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_firewall
  # Return the list of firewalls in the project
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @return [GetFirewall200Response]
  describe 'get_firewall test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_firewall_details
  # Get details of a specific firewall
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param [Hash] opts the optional parameters
  # @return [Firewall]
  describe 'get_firewall_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_location_firewall
  # Return the list of firewalls in the project and location
  # @param location The Ubicloud location/region
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @return [GetFirewall200Response]
  describe 'get_location_firewall test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_location_firewall_details
  # Get details of a specific firewall
  # @param location The Ubicloud location/region
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param [Hash] opts the optional parameters
  # @return [GetLocationFirewallDetails200Response]
  describe 'get_location_firewall_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
