=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Ubicloud::FirewallRuleApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FirewallRuleApi' do
  before do
    # run before each test
    @api_instance = Ubicloud::FirewallRuleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FirewallRuleApi' do
    it 'should create an instance of FirewallRuleApi' do
      expect(@api_instance).to be_instance_of(Ubicloud::FirewallRuleApi)
    end
  end

  # unit tests for create_firewall_rule
  # Create a new firewall rule
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param create_firewall_rule_request 
  # @param [Hash] opts the optional parameters
  # @return [FirewallRule]
  describe 'create_firewall_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_location_firewall_firewall_rule
  # Create a new firewall rule
  # @param location The Ubicloud location/region
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param firewall_rule_id ID of the firewall rule
  # @param create_firewall_rule_request 
  # @param [Hash] opts the optional parameters
  # @return [FirewallRule]
  describe 'create_location_firewall_firewall_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_location_firewall_rule
  # Create a new firewall rule
  # @param firewall_name Name of the firewall
  # @param location The Ubicloud location/region
  # @param project_id ID of the project
  # @param create_firewall_rule_request 
  # @param [Hash] opts the optional parameters
  # @return [FirewallRule]
  describe 'create_location_firewall_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_firewall_rule
  # Delete a specific firewall rule
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param firewall_rule_id ID of the firewall rule
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_firewall_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_location_firewall_firewall_rule
  # Delete a specific firewall rule
  # @param location The Ubicloud location/region
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param firewall_rule_id ID of the firewall rule
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_location_firewall_firewall_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_location_postgres_firewall_rule
  # Delete a specific firewall rule
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param postgres_database_name Postgres database name
  # @param firewall_rule_id ID of the postgres firewall rule
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_location_postgres_firewall_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_firewall_rule_details
  # Get details of a firewall rule
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param firewall_rule_id ID of the firewall rule
  # @param [Hash] opts the optional parameters
  # @return [FirewallRule]
  describe 'get_firewall_rule_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_location_firewall_firewall_rule_details
  # Get details of a firewall rule
  # @param location The Ubicloud location/region
  # @param project_id ID of the project
  # @param firewall_name Name of the firewall
  # @param firewall_rule_id ID of the firewall rule
  # @param [Hash] opts the optional parameters
  # @return [FirewallRule]
  describe 'get_location_firewall_firewall_rule_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
