=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Ubicloud::LoadBalancerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LoadBalancerApi' do
  before do
    # run before each test
    @api_instance = Ubicloud::LoadBalancerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoadBalancerApi' do
    it 'should create an instance of LoadBalancerApi' do
      expect(@api_instance).to be_instance_of(Ubicloud::LoadBalancerApi)
    end
  end

  # unit tests for attach_vm_location_load_balancer
  # Attach a VM to a Load Balancer in a specific location of a project
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param load_balancer_name Name of the load balancer
  # @param attach_vm_location_load_balancer_request 
  # @param [Hash] opts the optional parameters
  # @return [GetLoadBalancer200Response]
  describe 'attach_vm_location_load_balancer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_load_balancer
  # Create a new Load Balancer in a project
  # @param project_id ID of the project
  # @param load_balancer_name Name of the load balancer
  # @param create_load_balancer_request 
  # @param [Hash] opts the optional parameters
  # @return [GetLoadBalancer200Response]
  describe 'create_load_balancer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_location_load_balancer
  # Create a new Load Balancer in a specific location of a project
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param load_balancer_name Name of the load balancer
  # @param create_load_balancer_request 
  # @param [Hash] opts the optional parameters
  # @return [GetLoadBalancer200Response]
  describe 'create_location_load_balancer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_load_balancer
  # Delete a specific Load Balancer
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param load_balancer_name Name of the load balancer
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_load_balancer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for detach_vm_location_load_balancer
  # Detach a VM from a Load Balancer in a specific location of a project
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param load_balancer_name Name of the load balancer
  # @param detach_vm_location_load_balancer_request 
  # @param [Hash] opts the optional parameters
  # @return [GetLoadBalancer200Response]
  describe 'detach_vm_location_load_balancer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_load_balancer
  # Get details of a specific Load Balancer
  # @param project_id ID of the project
  # @param load_balancer_name Name of the load balancer
  # @param [Hash] opts the optional parameters
  # @return [GetLoadBalancer200Response]
  describe 'get_load_balancer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_load_balancer_details
  # Get details of a specific Load Balancer in a location
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param load_balancer_name Name of the load balancer
  # @param [Hash] opts the optional parameters
  # @return [GetLoadBalancer200Response]
  describe 'get_load_balancer_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_load_balancers
  # List Load Balancers in a specific project
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_after Pagination - Start after
  # @option opts [Integer] :page_size Pagination - Page size
  # @option opts [String] :order_column Pagination - Order column
  # @return [ListLoadBalancers200Response]
  describe 'list_load_balancers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_location_load_balancers
  # List Load Balancers in a specific location of a project
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_after Pagination - Start after
  # @option opts [Integer] :page_size Pagination - Page size
  # @option opts [String] :order_column Pagination - Order column
  # @return [ListLoadBalancers200Response]
  describe 'list_location_load_balancers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_location_load_balancer
  # Update a Load Balancer in a specific location of a project
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param load_balancer_name Name of the load balancer
  # @param patch_location_load_balancer_request 
  # @param [Hash] opts the optional parameters
  # @return [GetLoadBalancer200Response]
  describe 'patch_location_load_balancer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
