=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Ubicloud::LoginApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LoginApi' do
  before do
    # run before each test
    @api_instance = Ubicloud::LoginApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoginApi' do
    it 'should create an instance of LoginApi' do
      expect(@api_instance).to be_instance_of(Ubicloud::LoginApi)
    end
  end

  # unit tests for login
  # Login with user information
  # @param login_request 
  # @param [Hash] opts the optional parameters
  # @return [Login200Response]
  describe 'login test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
