=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Ubicloud::PostgresFirewallRuleApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PostgresFirewallRuleApi' do
  before do
    # run before each test
    @api_instance = Ubicloud::PostgresFirewallRuleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostgresFirewallRuleApi' do
    it 'should create an instance of PostgresFirewallRuleApi' do
      expect(@api_instance).to be_instance_of(Ubicloud::PostgresFirewallRuleApi)
    end
  end

  # unit tests for create_location_postgres_firewall_rule
  # Create a new postgres firewall rule
  # @param location The Ubicloud location/region
  # @param postgres_database_name Postgres database name
  # @param project_id ID of the project
  # @param create_location_postgres_firewall_rule_request 
  # @param [Hash] opts the optional parameters
  # @return [PostgresFirewallRule]
  describe 'create_location_postgres_firewall_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_location_postgres_firewall_rules
  # List location Postgres firewall rules
  # @param location The Ubicloud location/region
  # @param postgres_database_name Postgres database name
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @return [ListLocationPostgresFirewallRules200Response]
  describe 'list_location_postgres_firewall_rules test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
