=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Ubicloud::PrivateSubnetApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PrivateSubnetApi' do
  before do
    # run before each test
    @api_instance = Ubicloud::PrivateSubnetApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PrivateSubnetApi' do
    it 'should create an instance of PrivateSubnetApi' do
      expect(@api_instance).to be_instance_of(Ubicloud::PrivateSubnetApi)
    end
  end

  # unit tests for connect_private_subnet
  # Connect private subnet to another private subnet
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param private_subnet_name Private subnet name
  # @param connect_private_subnet_request 
  # @param [Hash] opts the optional parameters
  # @return [PrivateSubnet]
  describe 'connect_private_subnet test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_private_subnet
  # Create a new Private Subnet in a specific location of a project
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param private_subnet_name Private subnet name
  # @param [Hash] opts the optional parameters
  # @option opts [CreatePrivateSubnetRequest] :create_private_subnet_request 
  # @return [PrivateSubnet]
  describe 'create_private_subnet test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_private_subnet
  # Delete a specific Private Subnet
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param private_subnet_name Private subnet name
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_private_subnet test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for disconnect_private_subnet
  # Disconnect private subnet from another private subnet
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param private_subnet_name Private subnet name
  # @param private_subnet_id ID of the private subnet
  # @param [Hash] opts the optional parameters
  # @return [PrivateSubnet]
  describe 'disconnect_private_subnet test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_private_subnet_details
  # Get details of a specific Private Subnet in a location
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param private_subnet_name Private subnet name
  # @param [Hash] opts the optional parameters
  # @return [PrivateSubnet]
  describe 'get_private_subnet_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_location_private_subnets
  # List Private Subnets in a specific location of a project
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_after Pagination - Start after
  # @option opts [Integer] :page_size Pagination - Page size
  # @option opts [String] :order_column Pagination - Order column
  # @return [ListLocationPrivateSubnets200Response]
  describe 'list_location_private_subnets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_pss
  # List visible Private Subnets
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_after Pagination - Start after
  # @option opts [Integer] :page_size Pagination - Page size
  # @option opts [String] :order_column Pagination - Order column
  # @return [ListLocationPrivateSubnets200Response]
  describe 'list_pss test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
