=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Ubicloud::ProjectApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProjectApi' do
  before do
    # run before each test
    @api_instance = Ubicloud::ProjectApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectApi' do
    it 'should create an instance of ProjectApi' do
      expect(@api_instance).to be_instance_of(Ubicloud::ProjectApi)
    end
  end

  # unit tests for create_project
  # Create a new project
  # @param create_project_request 
  # @param [Hash] opts the optional parameters
  # @return [Project]
  describe 'create_project test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_project
  # Delete a project
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_project test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_object_info
  # Return information on object type, location, and name
  # @param project_id ID of the project
  # @param object_id ID of a supported object
  # @param [Hash] opts the optional parameters
  # @return [GetObjectInfo200Response]
  describe 'get_object_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_project
  # Retrieve a project
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @return [Project]
  describe 'get_project test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_projects
  # List all projects visible to the logged in user.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_after Pagination - Start after
  # @option opts [Integer] :page_size Pagination - Page size
  # @option opts [String] :order_column Pagination - Order column
  # @return [ListProjects200Response]
  describe 'list_projects test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
