=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Ubicloud::VirtualMachineApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VirtualMachineApi' do
  before do
    # run before each test
    @api_instance = Ubicloud::VirtualMachineApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VirtualMachineApi' do
    it 'should create an instance of VirtualMachineApi' do
      expect(@api_instance).to be_instance_of(Ubicloud::VirtualMachineApi)
    end
  end

  # unit tests for create_vm
  # Create a new VM in a specific location of a project
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param vm_name Virtual machine name
  # @param create_vm_request 
  # @param [Hash] opts the optional parameters
  # @return [GetVMDetails200Response]
  describe 'create_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_vm
  # Delete a specific VM
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param vm_name Virtual machine name
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_vm_details
  # Get details of a specific VM in a location
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param vm_name Virtual machine name
  # @param [Hash] opts the optional parameters
  # @return [GetVMDetails200Response]
  describe 'get_vm_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_location_vms
  # List VMs in a specific location of a project
  # @param location The Ubicloud location/region
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_after Pagination - Start after
  # @option opts [Integer] :page_size Pagination - Page size
  # @option opts [String] :order_column Pagination - Order column
  # @return [ListLocationVMs200Response]
  describe 'list_location_vms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_project_vms
  # List all VMs created under the given project ID and visible to logged in user
  # @param project_id ID of the project
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_after Pagination - Start after
  # @option opts [Integer] :page_size Pagination - Page size
  # @option opts [String] :order_column Pagination - Order column
  # @return [ListLocationVMs200Response]
  describe 'list_project_vms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for restart_vm
  # Restart a specific VM
  # @param project_id ID of the project
  # @param location The Ubicloud location/region
  # @param vm_name Virtual machine name
  # @param [Hash] opts the optional parameters
  # @return [GetVMDetails200Response]
  describe 'restart_vm test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
