# frozen_string_literal: true

# Use __dir__ to make sure that
# `BUNDLE_GEMFILE=rhizome/Gemfile bundle install` works from repository root,
# as that is what rhizome CI uses.

source "https://rubygems.org"

gem "netaddr"

if File.directory?(File.join(__dir__, "host"))
  gem "base64"

  group :test do
    gem "rspec"
  end
end
