=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Ubicloud::ActionLocationFirewallDetachSubnetRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Ubicloud::ActionLocationFirewallDetachSubnetRequest do
  let(:instance) { Ubicloud::ActionLocationFirewallDetachSubnetRequest.new }

  describe 'test an instance of ActionLocationFirewallDetachSubnetRequest' do
    it 'should create an instance of ActionLocationFirewallDetachSubnetRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Ubicloud::ActionLocationFirewallDetachSubnetRequest)
    end
  end

  describe 'test attribute "private_subnet_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
