=begin
#Clover API

#API for managing resources on Ubicloud

The version of the OpenAPI document: 0.1.0
Contact: support@ubicloud.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Ubicloud::CreateLocationPostgresMetricDestinationRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Ubicloud::CreateLocationPostgresMetricDestinationRequest do
  let(:instance) { Ubicloud::CreateLocationPostgresMetricDestinationRequest.new }

  describe 'test an instance of CreateLocationPostgresMetricDestinationRequest' do
    it 'should create an instance of CreateLocationPostgresMetricDestinationRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Ubicloud::CreateLocationPostgresMetricDestinationRequest)
    end
  end

  describe 'test attribute "password"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "username"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
