---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ubicloud-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.ubicloud.com
reclaimPolicy: Delete
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer
