name: Call Clickgres Builds

on:
  workflow_call:
    inputs:
      ubicloud-version:
        description: "Ubicloud version tag to pass to clickgres builds"
        required: true
        type: string
    secrets:
      WORKFLOW_AUTH_APP_ID:
        required: true
      WORKFLOW_AUTH_PRIVATE_KEY:
        required: true
      CLICKGRES_REPO:
        required: true

jobs:
  call-clickgres-builds:
    strategy:
      matrix:
        service:
          - api
          - workers
    runs-on: k8s-nano
    steps:
      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.WORKFLOW_AUTH_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_AUTH_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            ${{ secrets.CLICKGRES_REPO }}
      - name: Call workflow via gh
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh workflow run --repo ClickHouse/${{ secrets.CLICKGRES_REPO }} clickgres-${{ matrix.service }}.yml -f ubicloud-version=${{ inputs.ubicloud-version }}
