name: cli/ubi CI

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.tool-versions'
      - 'cli/**'
      - 'bin/ubi'
      - 'spec/cli_spec.rb'
      - '.github/workflows/cli-ci.yml'
      - '.github/actions/setup-clover/action.yml'
  pull_request:
    paths:
      - '.tool-versions'
      - 'cli/**'
      - 'bin/ubi'
      - 'spec/cli_spec.rb'
      - '.github/workflows/cli-ci.yml'
      - '.github/actions/setup-clover/action.yml'

jobs:
  cli-ci:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubicloud, ubicloud-arm]
    name: cli/ubi CI - ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}

    steps:
    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up Clover
      uses: ./.github/actions/setup-clover

    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: 'cli/go.mod'

    - name: Build cli/ubi
      run: bundle exec rake ubi

    - name: Run cli/ubi tests
      env:
        UBI_CMD: ./cli/ubi
      run: bundle exec rspec spec/cli_spec.rb

    - name: Run go fmt and check it makes no changes
      run: "cd cli && go fmt && git diff --stat --exit-code"

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
      with:
        version: v2.1.5
        working-directory: cli
