name: cli/ubi CI

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.tool-versions'
      - 'cli/**'
      - 'bin/ubi'
      - 'spec/cli_spec.rb'
      - '.github/workflows/cli-ci.yml'
      - '.github/actions/setup-clover/action.yml'
  pull_request:
    paths:
      - '.tool-versions'
      - 'cli/**'
      - 'bin/ubi'
      - 'spec/cli_spec.rb'
      - '.github/workflows/cli-ci.yml'
      - '.github/actions/setup-clover/action.yml'

jobs:
  cli-ci:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubicloud, ubicloud-arm]
    name: cli/ubi CI - ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}

    steps:
    - name: Check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Set up Clover
      uses: ./.github/actions/setup-clover

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: 'cli/go.mod'

    - name: Build cli/ubi
      run: bundle exec rake ubi

    - name: Run cli/ubi tests
      env:
        UBI_CMD: ./cli/ubi
      run: bundle exec rspec spec/cli_spec.rb

    - name: Run go fmt and check it makes no changes
      run: "cd cli && go fmt && git diff --stat --exit-code"

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: v2.1.5
        working-directory: cli
