name: kubernetes/csi CI

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.tool-versions'
      - 'kubernetes/csi/**'
      - '.github/workflows/kubernetes-csi-ci.yml'
  pull_request:
    paths:
      - '.tool-versions'
      - 'kubernetes/csi/**'
      - '.github/workflows/kubernetes-csi-ci.yml'

jobs:
  kubernetes-csi-ci:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubicloud-standard-2, ubicloud-standard-2-arm]
    name: Ruby CI - ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    timeout-minutes: 25

    steps:
    - name: Check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Set up Ruby for CSI gems
      uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
      env:
        BUNDLE_GEMFILE: kubernetes/csi/Gemfile
      with:
        ruby-version: mise.toml
        bundler-cache: true

    - name: Run CSI tests
      run: rake csi_spec
