name: kubernetes/csi CI

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.tool-versions'
      - 'kubernetes/csi/**'
      - '.github/workflows/kubernetes-csi-ci.yml'
  pull_request:
    paths:
      - '.tool-versions'
      - 'kubernetes/csi/**'
      - '.github/workflows/kubernetes-csi-ci.yml'

jobs:
  kubernetes-csi-ci:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubicloud-standard-2, ubicloud-standard-2-arm]
    name: Ruby CI - ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    timeout-minutes: 25

    steps:
    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up Ruby for CSI gems
      uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
      env:
        BUNDLE_GEMFILE: kubernetes/csi/Gemfile
      with:
        ruby-version: .tool-versions
        bundler-cache: true

    - name: Run CSI tests
      run: rake csi_spec
